#spring.application.name=journalApp

spring.mongodb.host = localhost
spring.mongodb.port = 27017
spring.mongodb.database = journaldb
#spring.data.mongodb.username = myusername
#spring.data.mongodb.password = mypassword

