#spring.application.name=journalApp

spring.data.mongodb.uri = mongodb+srv://pragya_02_gupta:<db_password>@cluster0.jbzmzyy.mongodb.net/?appName=Cluster0
spring.mongodb.database = journaldb
spring.data.mongodb.auto-index-creation=true

